<!--<div class="row">
	<div class="col-md-12">
		<article>
			<div class="panel panel-default">
				<div class="panel-heading">-->
						<tr> 
							<td><div class="panel-title"><?=$article ?></div></td>
							<td><div class="panel-title"><?=$price_per_kilo ?> €</div></td>
							<td><div class="panel-title"><?=$weight ?> kg</div></td>
							<td><div class="panel-title"><?=$monpanier2_price_total ?> €</div></td>	
						</tr>		
				<!--</div>
			</div>
		</article>
	</div>
</div>-->

