<div class="container">
	<div class="row">

        <form name="modification" method="post" action="">
            
            <div class="form-group">
                <label for="modifid" class="col-md-5 control-label formconfig">ID à modifier : </label>
                <div class="col-md-7">
                    <input type="text" name="id_client"  id="modifid" value="" placeholder="Entrer une ID" maxlength="64" class="form-control formconfig">
                </div>
            </div>

            
            <div class="form-group">
                <label for="modifpseudo" class="col-md-5 control-label formconfig">Pseudo à modifier : </label>
                <div class="col-md-7">
                    <input type="text" name="pseudo_client"  id="modifpseudo" value="" placeholder="Entrer un pseudo" maxlength="32" class="form-control formconfig">
                </div>
            </div>
            
            <button type="submit" name="valrecherche" class="col-md-12 formconfig">Valider</button>

        </form>

		<div class="col-md-6 col-sd-12" id="rechargeform">



			<form method="post" action="">
                <input type="hidden" name="id_client" value="<?=$identifiant?>">
				<fieldset>                

					<legend>Informations :</legend>

                    <!--BDD Client-->

					<div class="form-group">
                        <label for="formemail" class="col-md-5 control-label formconfig">Email : </label>
                        <div class="col-md-7">
                        	<input type="email" name="formemail"  id="formemail" value="<?=$email?>" placeholder="" maxlength="64" class="form-control formconfig">
                        </div>
                    </div>
                    <br>

                    <div class="form-group">
                        <label for="newphone" class="col-md-5 control-label formconfig">Téléphone : </label>
                        <div class="col-md-7">
                        	<input type="text" name="formphone"  id="newphone" value="<?=$phone?>" placeholder="" maxlength="16" class="form-control formconfig">
                        </div>
                    </div>
                    <br>

                    <!--BDD adresse-->

                <fieldset>

                    <legend>Adresse principale :</legend>

                    <div class="form-group">
                        <label for="newstreet" class="col-md-5 control-label formconfig">Rue : </label>
                        <div class="col-md-7">
                            <input type="text" name="formstreet"  id="newstreet" value="<?=$street?>" placeholder="" maxlength="16" class="form-control formconfig">
                        </div>
                    </div>
                    <br>

                    <div class="form-group">
                        <label for="newpostal" class="col-md-5 control-label formconfig">Code postal : </label>
                        <div class="col-md-7">
                            <input type="text" name="formzip"  id="newpostal" value="<?=$zipcode?>" placeholder="" maxlength="16" class="form-control formconfig">
                        </div>
                    </div>
                    <br>

                    <div class="form-group">
                        <label for="newcity" class="col-md-5 control-label formconfig">Ville : </label>
                        <div class="col-md-7">
                            <input type="text" name="formcity"  id="newcity" value="<?=$city?>" placeholder="" maxlength="32" class="form-control formconfig">
                        </div>
                    </div>
                    <br>

                    <div class="form-group">
                        <label for="newcountry" class="col-md-5 control-label formconfig">Pays : </label>
                        <div class="col-md-7">
                            <input type="text" name="formpays"  id="newcountry" value="<?=$country?>" placeholder="" maxlength="32" class="form-control formconfig">
                        </div>
                    </div>
                    <br>
                    

                </fieldset>


                <fieldset>

                    <legend>Adresse de livraison :</legend>

                    <div class="form-group">
                        <label for="newstreet" class="col-md-5 control-label formconfig">Rue : </label>
                        <div class="col-md-7">
                            <input type="text" name="formstreet2"  id="newstreet2" value="<?=$street2?>" placeholder="" maxlength="16" class="form-control formconfig">
                        </div>
                    </div>
                    <br>

                    <div class="form-group">
                        <label for="newpostal" class="col-md-5 control-label formconfig">Code postal : </label>
                        <div class="col-md-7">
                            <input type="text" name="formzip2"  id="newpostal2" value="<?=$zipcode2?>" placeholder="" maxlength="16" class="form-control formconfig">
                        </div>
                    </div>
                    <br>

                    <div class="form-group">
                        <label for="newcity" class="col-md-5 control-label formconfig">Ville : </label>
                        <div class="col-md-7">
                            <input type="text" name="formcity2"  id="newcity2" value="<?=$city2?>" placeholder="" maxlength="32" class="form-control formconfig">
                        </div>
                    </div>
                    <br>

                    <div class="form-group">
                        <label for="newcountry" class="col-md-5 control-label formconfig">Pays : </label>
                        <div class="col-md-7">
                            <input type="text" name="formpays2"  id="newcountry2" value="<?=$country2?>" placeholder="" maxlength="32" class="form-control formconfig">
                        </div>
                    </div>
                    <br>
                    

                </fieldset>



                    <button type="submit" name="validation" class="col-md-12 formconfig">Changer mes données</button>
                    

				</fieldset>
			</form>
		</div>

		<div class="col-md-6 col-sd-12">
			<form method="post" action="">
				<fieldset>

					<legend>Changement de mot de passe :</legend>


                    <div class="form-group">
                        <label for="nouveaupassword" class="col-md-5 control-label formconfig">Nouveau mot de passe : </label>
                        <div class="col-md-7">
                        	<input type="password" name="nouveaupassword"  id="nouveaupassword" value="" placeholder="Entrer votre nouveau mot de passe" maxlength="32" class="form-control formconfig">
                        </div>
                    </div>
                    <br>

                    <div class="form-group">
                        <label for="confirmpassword" class="col-md-5 control-label formconfig">Confirmation de mot de passe : </label>
                        <div class="col-md-7">
                        	<input type="password" name="confirmpassword"  id="confirmpassword" value="" placeholder="Confirmer votre nouveau mot de passe" maxlength="32" class="form-control formconfig">
                        </div>
                    </div>
                    <br>
                    
                    <button type="submit" name="validationmdp" class="col-md-12 formconfig">Modifier le mot de passe</button>

				</fieldset>


			</form>

		</div>
	</div>
</div>