<div class="row">
    <div class="col-md-12">
        <?= $message ?>
        <header class="page-header">
            <h1>Inscription <small>Devenez client !</small></h1>
        </header>
        <p>Les champs marqués d'un * sont obligatoires.</p>
        <form action="index.php?page=register" method="post">
        <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title">Informations principales</h3>
              </div>
              <div class="panel-body">
                <!-- Login -->
                <div class="form-group">
                    <label for="champLogin" class="col-sm-2 control-label">Identifiant :</label>
                    <div class="col-sm-10">
                        <input type="text" name="login"  value="<?= strip_tags($login) ?>" id="champLogin" placeholder="*" maxlength="32" class="form-control">
                    </div>
                </div>   

                <!-- Password -->
                <div class="form-group">
                    <label for="champPassword" class="col-sm-2 control-label">Mot de passe :</label>
                    <div class="col-sm-10">
                        <input type="password" name="password"  id="champPassword" placeholder="*" maxlength="32" class="form-control">
                    </div>
                 </div>

                <!-- civilité -->  
                <div class="form-group">
                    <label for="civility" class="col-sm-2 control-label">Civilité :</label>
                    <div class="col-sm-10">
                        <input type="radio" name="civility" id="champMonsieurs" value="M"/>
                        <label for="champMonsieurs">Monsieur</label>
                        <input type="radio" name="civility" id="champMadame" value="Mme" />
                        <label for="champMadame">Madame</label>
                        <input type="radio" name="civility" id="champMademoiselle" value="Mlle" />
                        <label for="champMademoiselle">Mademoiselle</label>                                
                    </div>
                </div>

                <!-- Nom -->
                <div class="form-group">
                    <label for="champFirstname" class="col-sm-2 control-label">Nom :</label>
                    <div class="col-sm-10">
                        <input type="text" name="firstname"  value="<?= strip_tags($firstname) ?>" id="champFirstname" placeholder="*" maxlength="32" class="form-control">
                    </div>
                </div>
                
                <!-- Prénom -->
                <div class="form-group">
                    <label for="lastName" class="col-sm-2 control-label">Prénom :</label>
                    <div class="col-sm-10">
                        <input type="text" name="lastname"  id="champLastName" value="<?= strip_tags($lastname) ?>" placeholder="*" maxlength="32" class="form-control">
                    </div>
                 </div>

                <!-- email -->                         
                <div class="form-group">
                    <label for="champEmail" class="col-sm-2 control-label">Email :</label>
                    <div class="col-sm-10">
                        <input type="email" name="email"  value="<?= strip_tags($email) ?>" id="champEmail" maxlength="64" placeholder="*" class="form-control">
                    </div>
                 </div>

                <!-- phone -->                         
                <div class="form-group">
                    <label for="champPhone" class="col-sm-2 control-label">Téléphone :</label>
                    <div class="col-sm-10">
                        <input type="text" name="phone"  value="<?= strip_tags($phone) ?>" id="champPhone" maxlength="16" class="form-control">
                    </div>
                 </div>
                <input type="hidden" name="captchaGen" value="<?= $captchaGen; ?>">
                <div class="form-group">              
                    <label for="captcha" class="col-sm-2 control-label">Recopiez le mot : "<?= $captchaGen; ?>"</label>
                    <div class="col-sm-10">
                        <input type="text" name="captcha" id="captcha" value="<?= strip_tags($captcha) ?>" maxlength="6" class="form-control"/><br />
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Adresse principale (adresse par défaut, peut être changée ultérieurement)</h3>
            </div>
            <div class="panel-body">
                <!-- street -->                         
                <div class="form-group">
                    <label for="champStreet" class="col-sm-2 control-label">N° et nom de rue : </label>
                    <div class="col-sm-10">
                        <input type="text" name="street"  value="<?= strip_tags($street) ?>" id="champStreet" maxlength="64" placeholder="*" class="form-control">
                    </div>
                 </div>

                <!-- zipcode -->                         
                <div class="form-group">
                    <label for="champZipcode" class="col-sm-2 control-label">Code postal : </label>
                    <div class="col-sm-10">
                        <input type="text" name="zipcode"  value="<?= strip_tags($zipcode) ?>" id="champZipcode" maxlength="16" placeholder="*" class="form-control">
                    </div>
                 </div>

                <!-- City -->
                <div class="form-group">
                    <label for="champCity" class="col-sm-2 control-label">Ville : </label>
                    <div class="col-sm-10">
                        <input type="text" name="city"  id="champCity" value="<?= strip_tags($city) ?>" maxlength="32" placeholder="*" class="form-control">
                    </div>
                 </div>

                <!-- Country -->
                <div class="form-group">
                    <label for="champCountry" class="col-sm-2 control-label">Pays : </label>
                    <div class="col-sm-10">
                        <input type="text" name="country"  id="champCountry" value="<?= strip_tags($country) ?>" maxlength="32" placeholder="*" class="form-control">
                    </div>
                 </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <button type="submit" class="btn btn-primary" placeholder="*" name="register">S'enregistrer</button>
            </div>
        </div>
        </form>
    </div>
</div>