<div class="row">
	<div class="col-md-12">
		<header class="jumbotron">
		  <h1>Eshop</h1>
		  <p>Vente de fruits & légumes frais et pas périmés !== Leclerc Drive</p>
		</header>
	</div>
	<div class="col-md-9">
		<h2>Nos 5 derniers produits</h2>
		<div class="table-responsive">
			<table class="table table-striped">
			<thead>
				<th>Produit</th>
				<th>Description</th>
				<th>Origine</th>
			</thead>
			<?php
			displayLoop1($displayLastProd);
			?>
			</table>
		</div>
	</div>
	<div class="col-md-3">
		<h2>Bientôt épuisés</h2>
		<div class="table-responsive">
			<table class="table table-striped">
			<thead>
				<th>Produit</th>
				<th>Stock (kg)</th>
			</thead>
			<?php
			displayLoop2($displayLowStock);
			?>
			</table>
		</div>
	</div>
</div>