</section>
<footer class="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<h4 class="text-uppercase">Share</h4>
				<ul class="social-list">
                	<li><a href="#" class="social social-fb"></a></li>
                	<li><a href="#" class="social social-tw"></a></li>
                	<li><a href="#" class="social social-db"></a></li>
                	<li><a href="#" class="social social-rss"></a></li>
				</ul>
			</div>
			<div class="col-md-4">
				<h4 class="text-uppercase">Privacy policy</h4>
			</div>
			<div class="col-md-4">
				<h4 class="text-uppercase">Quick links</h4>
			</div>
		</div>
	</div>
</footer>