<!DOCTYPE html>
<html lang="fr">
	<head>
	    <meta charset="utf-8">

	    <title>Eshop</title>

	    <meta name="viewport" content="width=device-width, maximum-scale=1.0">
		<script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>
		<script type="text/javascript" src="js/bootstrap.min.js"></script>
		<script type="text/javascript" src="js/jquery.bxslider.min.js"></script>
		<script type="text/javascript" src="js/tinymce/tinymce.min.js"></script>
		<script type="text/javascript" src="js/myscript.js"></script>
		<script type="text/javascript" src="js/search.js"></script>

        <link rel="stylesheet" href="style/bootstrap.min.css" />
        <link rel="stylesheet" href="style/jquery.bxslider.css" />
        <link rel="stylesheet" href="style/style.css" />
	</head>
	<body>
			<?php require('apps/header.php'); ?>
			<?php require($pageName.'/index.php'); ?>
			<?php require('apps/footer.php'); ?>
	</body>
</html>