<!DOCTYPE html>
<html lang="fr">
	<head>
	    <meta charset="utf-8">
	    <title>CIN3WA</title>
	    <meta name="viewport" content="width=device-width, maximum-scale=1.0">
		<script type="text/javascript" src=<?= $path.'js/jquery-2.1.4.min.js';?>></script>
		<script type="text/javascript" src=<?= $path.'js/bootstrap.min.js';?>></script>
		<script type="text/javascript" src=<?= $path.'js/jquery.bxslider.min.js';?>></script>
		<script type="text/javascript" src=<?= $path.'js/tinymce/tinymce.min.js';?>></script>
		<script type="text/javascript" src=<?= $path.'js/myscript.js';?>></script>
        <link rel="stylesheet" href=<?= $path.'style/bootstrap.min.css';?> />
        <link rel="stylesheet" href=<?= $path.'style/jquery.bxslider.css';?> />
        <link rel="stylesheet" href=<?= $path.'style/style.css';?> />
	</head>
	<body>
			<?php require('apps/header.php'); ?>
			<?php require($pageName.'/index.php'); ?>
			<?php require('apps/footer.php'); ?>
	</body>
</html>