<p>
	<a href="index.php?page=panier&order_id=<?=$selectcv9['monpanier1a_orderid']?>">
		<button type="button" class="btn btn-primary">
			Voir le panier
		</button>
	</a>
</p>

	            <strong><?= isset($_SESSION["id"]) ?> ? <p><a href="index.php?page=panier&order_id=<?=$selectcv9['monpanier1a_orderid']?>">
					<button type="button" class="btn btn-primary">Voir le panier</button></a></p> :<?php ""; ?></strong> 


