<div class="row">
	<!-- affichage du titre de l"'article en grand et au centre de la page-->
	<div class="col-md-12 title">	
		<h2><strong><?= strip_tags($selectsc3['myproduct3_subcategoryname']) ?></strong> &rarr; <?= strip_tags($selectsc3['myproduct3_name']) ?></h2>
	</div>
	<div class="col-md-3">
		<img src=<?= strip_tags($selectsc3['myproduct3_image']) ?> >
	</div>
	<div class="col-md-9">
		<p><strong><?= nl2br(strip_tags($selectsc3['myproduct3_description'])) ?></strong></p>
		<p><strong>Prix : </strong><?= strip_tags($selectsc3['myproduct3_price']) ?> €/kg</p>
		<p><strong>Origine : </strong><?= strip_tags($selectsc3['myproduct3_origine']) ?></p>
		<p><strong>Quantité en stock : </strong><?= strip_tags($selectsc3['myproduct3_stockquantity']) ?> kg</p>
		<?php
		displayAvis($selectsc3['myproduct3_idproduct']);
		?>
		<p><a href="index.php?page=catalogue&id_subcategory=<?=$selectsc3['myproduct3_subcategoryid']?>"><button type="button" class="btn btn-primary">
					Retour vers la sous catégorie <strong><?=$selectsc3['myproduct3_subcategoryname']?></strong> </button></a>
		</p>
		<p><a href="index.php?page=catalogue"><button type="button" class="btn btn-primary">Retour vers le catalogue général</button></a>
		</p>
		<form method="post" action="index.php?page=ajout_panier&id_product=<?=$selectsc3['myproduct3_idproduct']?>" enctype="multipart/form-data">	
            <div class="form-group">
                <label for="champAmount">Quantité à commander (kg)</label>
                <input type="text" name="amount"  value="<?php echo strip_tags($amount) ?>" id="champAmount" placeholder="0" maxlength="10" class="form-control">
            </div>
            <div class="form-group">
                <button type="submit" name="ajout_panier" class="btn btn-primary">Ajouter au panier</button>
            </div>
        </form>
	</div>
</div>