
<div class="row fiche-produit">

	<!-- affichage du titre de l"'article en grand et au centre de la page-->
	<div class="col-md-12 title">
		
		<h2><strong><?=strip_tags($selectsc3['myproduct3_subcategoryname']) ?></strong> - <?=strip_tags($selectsc3['myproduct3_name']) ?></h2>
	</div>

	<div class="col-md-6 image-product">
		<h2> <img src=<?=strip_tags($selectsc3['myproduct3_image']) ?> ></h2>
	</div>

	<div class="col-md-6 content-product">
		<p><strong><?=strip_tags($selectsc3['myproduct3_description']) ?></strong></p>
		<p><?=strip_tags($selectsc3['myproduct3_price']) ?> €/kg</p>
		<p><?= "origine : " . strip_tags($selectsc3['myproduct3_origine']) ?></p>
		<p><?= "quantité en stock : " . strip_tags($selectsc3['myproduct3_stockquantity']) ?> kg</p>
		<p>
			<div class="lien"><a href="index.php?page=note&id_product=<?=$selectsc3['myproduct3_idproduct']?>">
					<button type="button" class="btn btn-primary" width="200px">donner votre avis</button></a>
					<!--<img src="images/star.png" alt="star"/><img src="images/star.png" alt="star"/><img src="images/star.png" alt="star"/><img src="images/star.png" alt="star"/><img src="images/star.png" alt="star"/>-->
			</div>
		</p>
		<p><a href="index.php?page=catalogue&id_subcategory=<?=$selectsc3['myproduct3_subcategoryid']?>"><button type="button" class="btn btn-primary">
					Retour vers la sous catégorie <strong><?=$selectsc3['myproduct3_subcategoryname']?></strong> </button></a></p>
		<p><a href="index.php?page=catalogue"><button type="button" class="btn btn-primary">Retour vers le catalogue général</button></a></p>
		<p>


			<form method="post" action="index.php?page=ajout_panier&id_product=<?=$selectsc3['myproduct3_idproduct']?>" enctype="multipart/form-data">	
				
	            
	             <div class="col-md-6 long6">
	                <label for="champAmount" class="">Quantité à commander</label>
	            </div>          
	            <div class="col-md-2 long2">
	                <input type="text" name="amount"  value="<?php echo strip_tags($amount) ?>" id="champAmount" placeholder="0" maxlength="10" class="form-control">
	            </div>
	            <div class="col-md-1 long1">
	                <label > kg</label>
	            </div>

	            <div class="col-md-6 long6">               
	                <button type="submit" name="ajout_panier" class="btn btn-primary">Ajouter au panier</button>
	            </div>
	        </form>
        </p>
	

	</div>

</div>


<style>

	.title{
		text-align: center;
		font-size: 30px;
		text-transform: uppercase;
		color:rgb(0,220,150);
		margin: 30px 0;
	}

	.fiche-produit{
		overflow: hidden;
		margin: 0 auto;
	}

	.image-product, .content-product{
		float:left;
		width:50%;
		max-height: 400px;
		margin : 0;
		font-size: 20px;
	}

	.long2, .long6, .long1{
		padding-left:0;
	}

	.content-product{
		margin: 50px 0;
	}

	img{
		width : 100%;
	}

	.lien{
		vertical-align: bottom;
	}

	.lien img{
		width : 16px;
	}

	/*button{
		width: 350px;
	}*/

</style>


