<div class="row">
	<div class="col-md-6">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title">Informations principales</h3>
			</div>
			<div class="panel-body">
				<p>blablabla</p>
			</div>
		</div>
	</div>
	<div class="col-md-6">
		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title">Statistiques</h3>
			</div>
			<div class="panel-body">
				<p>blablabla</p>
			</div>
		</div>
	</div>
</div>