<div class="row">

	<div class="col-md-12"><?= $message ?>
	</div>
	<div class="col-md-12 ">

 		<p id="pagination"><?= 'Go to page:'.implode("", pagination($pagin, $nbPage, 3, '?page=catalogue&amp;id_subcategory=' .$_GET['id_subcategory']. '&pagin='));?></p>
		<div class="table-responsive">
			<table class="table table-striped">
				<thead>
					<th>Nom</th>
					<th>Prix</th>
					<th>Origine</th>
					<th>Image</th>
					<th>Quantité disponible en stock</th>
				</thead>
				<?php
				displayLoop($selectsc2);
				?>
			</table>
			<a href="index.php?page=catalogue"><button type="button" class="btn btn-primary">Retour vers le catalogue</button></a>
		</div> 
	</div>
</div>

<style>

	.title{
		text-align: center;
		font-size: 30px;
		text-transform: uppercase;
		color:rgb(0,220,150);
		margin: 30px 0;
	}

</style>