<div>Prix total du panier : <?php echo $super_total ?> €</div>

<br>

<a href="index.php?page=validation_panier&id_order=<?=$order[0]['id']?>">
<!-- <button id="valider">Valider la commande</button> -->
<button id="retour"><img alt="" src="http://www.fancyicons.com/free-icons/103/office/png/256/back_256.png">Retourner au catalogue</button>
<button type="button" class="btn btn-primary" width="200px">valider le panier</button>