<?php require '../apps/header.php'; ?>

<div class="row">
	<?php $products = $db->query('SELECT * FROM product')->fetchAll(); ?>
	<?php foreach ( $products as $product ): ?>
		<div class="product full">
				<a href="#">
					<img src="<?= $product['image']; ?>" height="100px"/>
				</a>
				<div class="description">
					<?= $product['name']; ?>
					<a href="#" class="price"><?= $product['price']; ?> €</a>
				</div>
				<a class="add addPanier" href="addpanier.php?id=<?= $product['id_product']; ?>">
					add
				</a>
		</div>
	<?php endforeach ?>
</div>


<a href="index.php?page=validation_panier&id_order=<?=$order[0]['id']?>">
<!-- <button id="valider">Valider la commande</button> -->
<button id="retour"><img alt="" src="http://www.fancyicons.com/free-icons/103/office/png/256/back_256.png">Retourner au catalogue</button>
<button type="button" class="btn btn-primary" width="200px">valider le panier</button>

<div id="pagination">
	<ul class="wrap">
		<li><a href="#"> Prev </a></li>
		<li class="page"> Page : <a href="#">1</a> of 3</li>
		<li><a href="#"> Next</a></li>
	</ul>
</div>


<?php require 'apps/footer.php'; ?>