<div class="row">
	<div class="col-md-2 resultpanier">
		<span>Nom</span>
		<?php echo $name ?>
	</div>
	<div class="col-md-2 resultpanier">
		<span>Poids</span>
		<?php echo $weight ?> kg
	</div>
	<div class="col-md-2 resultpanier">
		<span>Prix au kilogramme</span>
		<?php echo $price_per_kilo ?> €
	</div>
	<div class="col-md-2 resultpanier">
		<span>Prix total</span>
		<?php echo $price_total ?> €
	</div>
	<form class="col-md-2 annulpanier" action="index.php?page=panier&action=annuler" method="POST">
		<input type="hidden" name='my_id' value="<?= $my_id ?>">
		<input type="submit" value="X">
	</form>
</div>