<div class="row">
		<div class="col-md-2 resultpanier"> <?php echo $id_product ?> </div>
		<div class="col-md-2 resultpanier"> <?php echo $weight ?> </div>
		<div class="col-md-2 resultpanier"> <?php echo $price_per_kilo ?> €</div>
		<div class="col-md-2 resultpanier"> <?php echo $price_total ?> €</div>
		<form class="col-md-2 annulpanier" action="index.php?page=panier&action=annuler" method="POST">
			<input type="hidden" name='id_product' value="2">
			<input type="submit" value="X">
		</form>
</div>
<style>
	.resultpanier{
		display:inline-block;
		width:200px;
		border:1px solid black;
	}
	.annulpanier{
		display: inline-block;
	}
</style>